.PHONY: all build clean install test build-tests test-avx10 test-rax coverage

BUILD_DIR := build
INSTALL_DIR := $(HOME)/.idapro/plugins

# Detect platform and set plugin extension
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Darwin)
    PLUGIN_EXT := dylib
else
    PLUGIN_EXT := so
endif
PLUGIN_NAME := lifter.$(PLUGIN_EXT)

# Find IDA SDK - check common locations
ifndef IDASDK
    ifneq (,$(wildcard $(HOME)/ida-sdk))
        IDASDK := $(HOME)/ida-sdk
    else ifneq (,$(wildcard $(HOME)/idasdk91))
        IDASDK := $(HOME)/idasdk91
    endif
endif

# ida_add_plugin() writes the built plugin into the SDK's plugin output dir.
# Packaged/zip SDKs (incl. the ones generated by IDA's own `sdk-package`
# target) use the classic "bin/plugins" layout; GitHub SDK clones use
# "src/bin/plugins". Probe both so `make install` works against either.
IDA_SDK_PLUGIN_DIRS := $(IDASDK)/bin/plugins $(IDASDK)/src/bin/plugins

all: build

build:
	@mkdir -p $(BUILD_DIR)
	@cd $(BUILD_DIR) && cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
	@cd $(BUILD_DIR) && ninja

install: build
	@mkdir -p $(INSTALL_DIR)
	@found=""; \
	for d in $(IDA_SDK_PLUGIN_DIRS); do \
		if [ -f "$$d/$(PLUGIN_NAME)" ]; then found="$$d/$(PLUGIN_NAME)"; break; fi; \
	done; \
	if [ -n "$$found" ]; then \
		cp "$$found" "$(INSTALL_DIR)/"; \
	else \
		echo "Error: $(PLUGIN_NAME) not found in: $(IDA_SDK_PLUGIN_DIRS)"; \
		exit 1; \
	fi
ifeq ($(UNAME_S),Darwin)
	@codesign -s - -f "$(INSTALL_DIR)/$(PLUGIN_NAME)" 2>/dev/null || true
endif
	@echo "Installed $(PLUGIN_NAME) to $(INSTALL_DIR)"

test:
	@$(MAKE) -C test test

# Coverage-closure gate: fail if any dispatched itype is never exercised with a
# memory-source operand (and isn't allowlisted). See test/torture/coverage_closure.py.
coverage:
	@$(MAKE) -C test/torture coverage

build-tests:
	@$(MAKE) -C test build

test-avx10:
	@$(MAKE) -C test experimental_avx10

test-rax:
	@$(MAKE) -C test experimental_rax

clean:
	@rm -rf $(BUILD_DIR)
