var f;f||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,k=!!globalThis.WorkerGlobalScope,m=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,ba=[],ca="./this.program",da=(a,b)=>{throw b;},ea=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ea=__filename:k&&(ea=self.location.href);var fa="",ha,v;
if(m){var fs=require("fs");fa=__dirname+"/";v=a=>{a=ia(a)?new URL(a):a;return fs.readFileSync(a)};ha=async a=>{a=ia(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);da=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||k){try{fa=(new URL(".",ea)).href}catch{}k&&(v=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ha=async a=>{if(ia(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ja=console.log.bind(console),x=console.error.bind(console),y,z=!1,ka,ia=a=>a.startsWith("file://"),A,la,B;
function ma(){var a=na.buffer;A=new Int8Array(a);new Int16Array(a);la=new Uint8Array(a);new Uint16Array(a);new Int32Array(a);B=new Uint32Array(a);new Float32Array(a);new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}function D(a){f.onAbort?.(a);a="Aborted("+a+")";x(a);z=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var oa;
async function pa(a){if(!y)try{var b=await ha(a);return new Uint8Array(b)}catch{}if(a==oa&&y)a=new Uint8Array(y);else if(v)a=v(a);else throw"both async and sync fetching of the wasm failed";return a}async function qa(a,b){try{var c=await pa(a);return await WebAssembly.instantiate(c,b)}catch(d){x(`failed to asynchronously prepare wasm: ${d}`),D(d)}}
async function ra(a){var b=oa;if(!y&&!ia(b)&&!m)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){x(`wasm streaming compile failed: ${d}`),x("falling back to ArrayBuffer instantiation")}return qa(b,a)}class sa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ta=a=>{for(;0<a.length;)a.shift()(f)},ua=[],va=[],wa=()=>{var a=f.preRun.shift();va.push(a)},E=0,F=null,xa=()=>{E--;f.monitorRunDependencies?.(E);if(0==E&&F){var a=F;F=null;a()}},ya=()=>{E++;f.monitorRunDependencies?.(E)},za=!0,Aa=0,G={},Ba=a=>{a instanceof sa||"unwind"==a||da(1,a)},Ca=a=>{ka=a;za||0<Aa||(f.onExit?.(a),z=!0);da(a,new sa(a))},Da=()=>{if(!(za||0<Aa))try{var a=ka;ka=a;Ca(a)}catch(b){Ba(b)}},Ea=a=>{if(!z)try{a(),Da()}catch(b){Ba(b)}},La=(a,b)=>{Fa=a;Ga=b;if(H)if(Ha||=!0,0==a)I=function(){setTimeout(J,
Math.max(0,Ia+b-performance.now())|0)};else if(1==a)I=function(){Ja(J)};else if(2==a){if(!Ka)if(globalThis.setImmediate)Ka=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ka=d=>{c.push(d);if(k){let e;(e=f).setImmediates??(e.setImmediates=[]);f.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}I=function(){Ka(J)}}},Ua=(a,b,c,d,e)=>{function g(){return h<
Ma?(Da(),!1):!0}H=a;Na=d;var h=Ma;Ha=!1;J=function(){if(!z)if(0<Oa.length){var q=Oa.shift();q.ua(q.la);if(Pa){var p=Pa,l=0==p%1?p-1:Math.floor(p);Pa=q.ra?l:(8*p+(l+.5))/9}f.setStatus&&(q=f.statusMessage||"Please wait...",p=Pa??0,l=Qa.ta??0,p?p<l?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(q):f.setStatus(""));g()&&setTimeout(J,0)}else if(g())if(Ra=Ra+1|0,1==Fa&&1<Ga&&0!=Ra%Ga)I();else{0==Fa&&(Ia=performance.now());a:if(!z){for(q of Sa)if(!1===q())break a;Ea(a);for(p of Ta)p()}g()&&
I()}};e||(0<b?La(0,1E3/b):La(1,1),I());if(c)throw"unwind";},Ha=!1,I=null,Ma=0,H=null,Na=0,Fa=0,Ga=0,Ra=0,Oa=[],Sa=[],Ta=[];function Va(){I=null;Ma++}var M=0;function Ja(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===M)M=b+1E3/60;else for(;b+2>=M;)M+=1E3/60;setTimeout(a,Math.max(M-b,0))}}
var Qa={},Ia,J,Ka,Pa,Wa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},N=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Wa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Xa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Ya=
()=>{if(m){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Za=a=>{(Za=Ya())(a)},$a=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Wa(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},ab=new TextDecoder,bb=a=>{var b=0;for(var c=b+void 0;a[b]&&!(b>=c);)++b;return ab.decode(a.buffer?a.subarray(0,
b):new Uint8Array(a.slice(0,b)))},cb=[],db=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},eb=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.codePointAt(g);if(127>=h){if(c>=d)break;b[c++]=h}else if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6;b[c++]=128|h&63}else if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12;b[c++]=128|h>>6&63;b[c++]=128|h&63}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=
128|h>>12&63;b[c++]=128|h>>6&63;b[c++]=128|h&63;g++}}b[c]=0;return c-e},fb=a=>{var b=Array(db(a)+1);a=eb(a,b,0,b.length);b.length=a;return b},gb=[];function hb(a,b){gb[a]={input:[],output:[],J:b};ib(a,jb)}
var jb={open(a){var b=gb[a.node.rdev];if(!b)throw new O(43);a.tty=b;a.seekable=!1},close(a){a.tty.J.fsync(a.tty)},fsync(a){a.tty.J.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.J.Z)throw new O(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.J.Z(a.tty)}catch(q){throw new O(29);}if(void 0===h&&0===e)throw new O(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.J.S)throw new O(60);try{for(var e=0;e<d;e++)a.tty.J.S(a.tty,b[c+e])}catch(g){throw new O(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},kb={Z(){a:{if(!cb.length){var a=null;if(m){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}cb=fb(a)}a=cb.shift()}return a},S(a,b){null===b||10===b?(ja(bb(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&
(ja(bb(a.output)),a.output=[])},xa(){return{oa:25856,qa:5,na:191,pa:35387,ma:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},ya(){return 0},za(){return[24,80]}},lb={S(a,b){null===b||10===b?(x(bb(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(x(bb(a.output)),a.output=[])}},P={C:null,F(){return P.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new O(63);P.C||(P.C={dir:{node:{H:P.u.H,D:P.u.D,
lookup:P.u.lookup,M:P.u.M,rename:P.u.rename,unlink:P.u.unlink,rmdir:P.u.rmdir,readdir:P.u.readdir,symlink:P.u.symlink},stream:{B:P.v.B}},file:{node:{H:P.u.H,D:P.u.D},stream:{B:P.v.B,read:P.v.read,write:P.v.write,R:P.v.R,ba:P.v.ba}},link:{node:{H:P.u.H,D:P.u.D,readlink:P.u.readlink},stream:{}},Y:{node:{H:P.u.H,D:P.u.D},stream:mb}});c=nb(a,b,c,d);Q(c.mode)?(c.u=P.C.dir.node,c.v=P.C.dir.stream,c.s={}):32768===(c.mode&61440)?(c.u=P.C.file.node,c.v=P.C.file.stream,c.A=0,c.s=null):40960===(c.mode&61440)?
(c.u=P.C.link.node,c.v=P.C.link.stream):8192===(c.mode&61440)&&(c.u=P.C.Y.node,c.v=P.C.Y.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.s[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},va(a){return a.s?a.s.subarray?a.s.subarray(0,a.A):new Uint8Array(a.s):new Uint8Array(0)},u:{H(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;Q(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.A:40960===(a.mode&61440)?b.size=a.link.length:b.size=
0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},D(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.A!=b&&(0==b?(a.s=null,a.A=0):(c=a.s,a.s=new Uint8Array(b),c&&a.s.set(c.subarray(0,Math.min(b,a.A))),a.A=b)))},lookup(){P.N||(P.N=new O(44),P.N.stack="<generic error, no stack>");throw P.N;},M(a,b,c,d){return P.createNode(a,b,c,d)},rename(a,b,c){try{var d=
R(b,c)}catch(g){}if(d){if(Q(a.mode))for(var e in d.s)throw new O(55);ob(d)}delete a.parent.s[a.name];b.s[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.s[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=R(a,b),d;for(d in c.s)throw new O(55);delete a.s[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.s)]},symlink(a,b,c){a=P.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new O(28);return a.link}},
v:{read(a,b,c,d,e){var g=a.node.s;if(e>=a.node.A)return 0;a=Math.min(a.node.A-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write(a,b,c,d,e,g){b.buffer===A.buffer&&(g=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.s||a.s.subarray)){if(g)return a.s=b.subarray(c,c+d),a.A=d;if(0===a.A&&0===e)return a.s=b.slice(c,c+d),a.A=d;if(e+d<=a.A)return a.s.set(b.subarray(c,c+d),e),d}g=e+d;var h=a.s?a.s.length:0;h>=g||(g=Math.max(g,h*(1048576>
h?2:1.125)>>>0),0!=h&&(g=Math.max(g,256)),h=a.s,a.s=new Uint8Array(g),0<a.A&&a.s.set(h.subarray(0,a.A),0));if(a.s.subarray&&b.subarray)a.s.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.s[e+g]=b[c+g];a.A=Math.max(a.A,e+d);return d},B(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.A);if(0>b)throw new O(28);return b},R(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new O(43);a=a.node.s;if(e&2||!a||a.buffer!==A.buffer){d=!0;D();e=void 0;if(!e)throw new O(48);if(a){if(0<c||
c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);A.set(a,e)}}else d=!1,e=a.byteOffset;return{Ba:e,ka:d}},ba(a,b,c,d){P.v.write(a,b,0,d,c,!1);return 0}}},pb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},qb=async a=>{a=await ha(a);return new Uint8Array(a)},rb=[],sb=async(a,b)=>{"undefined"!=typeof Browser&&Browser.wa();for(var c of rb)if(c.canHandle(b))return c.handle(a,b);return a},tb=null,ub={},S=[],vb=1,T=null,wb=!1,xb=!0,yb={},O=class{name="ErrnoError";constructor(a){this.L=
a}},zb=class{G={};node=null;get flags(){return this.G.flags}set flags(a){this.G.flags=a}get position(){return this.G.position}set position(a){this.G.position=a}},Ab=class{u={};v={};K=null;constructor(a,b,c,d){a||=this;this.parent=a;this.F=a.F;this.id=vb++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=
-147}get ga(){return Q(this.mode)}get fa(){return 8192===(this.mode&61440)}};
function U(a,b={}){if(!a)throw new O(44);b.P??(b.P=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(q=>!!q);for(var d=tb,e="/",g=0;g<a.length;g++){var h=g===a.length-1;if(h&&b.parent)break;if("."!==a[g])if(".."===a[g])if(e=Xa(e),d===d.parent){a=e+"/"+a.slice(g+1).join("/");c--;continue a}else d=d.parent;else{e=N(e+"/"+a[g]);try{d=R(d,a[g])}catch(q){if(44===q?.L&&h&&b.ia)return{path:e};throw q;}!d.K||h&&!b.P||(d=d.K.root);if(40960===(d.mode&61440)&&(!h||b.O)){if(!d.u.readlink)throw new O(52);
d=d.u.readlink(d);"/"===d.charAt(0)||(d=Xa(e)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:e,node:d}}throw new O(32);}function V(a){for(var b;;){if(a===a.parent)return a=a.F.aa,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Bb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%T.length}function ob(a){var b=Bb(a.parent.id,a.name);if(T[b]===a)T[b]=a.I;else for(b=T[b];b;){if(b.I===a){b.I=a.I;break}b=b.I}}
function R(a,b){var c=Q(a.mode)?(c=W(a,"x"))?c:a.u.lookup?0:2:54;if(c)throw new O(c);for(c=T[Bb(a.id,b)];c;c=c.I){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.u.lookup(a,b)}function nb(a,b,c,d){a=new Ab(a,b,c,d);b=Bb(a.parent.id,a.name);a.I=T[b];return T[b]=a}function Q(a){return 16384===(a&61440)}function Cb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function W(a,b){if(xb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Db(a,b){if(!Q(a.mode))return 54;try{return R(a,b),20}catch(c){}return W(a,"wx")}function Eb(a){a=S[a];if(!a)throw new O(8);return a}function Fb(a,b){var c=null?.v.D,d=c?null:a;c??=a.u.D;if(!c)throw new O(63);c(d,b)}var mb={open(a){a.v=ub[a.node.rdev].v;a.v.open?.(a)},B(){throw new O(70);}};function ib(a,b){ub[a]={v:b}}
function Gb(a,b){var c="/"===b;if(c&&tb)throw new O(10);if(!c&&b){var d=U(b,{P:!1});b=d.path;d=d.node;if(d.K)throw new O(10);if(!Q(d.mode))throw new O(54);}b={type:a,Aa:{},aa:b,ha:[]};a=a.F(b);a.F=b;b.root=a;c?tb=a:d&&(d.K=b,d.F&&d.F.ha.push(b))}function Hb(a,b,c){var d=U(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new O(28);if("."===a||".."===a)throw new O(20);var e=Db(d,a);if(e)throw new O(e);if(!d.u.M)throw new O(63);return d.u.M(d,a,b,c)}
function Ib(a,b=438){return Hb(a,b&4095|32768,0)}function X(a){return Hb(a,16895,0)}function Jb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Hb(a,b|8192,c)}function Kb(a,b){if(!$a(a))throw new O(44);var c=U(b,{parent:!0}).node;if(!c)throw new O(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=Db(c,b);if(d)throw new O(d);if(!c.u.symlink)throw new O(63);c.u.symlink(c,b,a)}
function Lb(a){var b=U(a,{parent:!0}).node;if(!b)throw new O(44);a=a&&a.match(/([^\/]+|\/)\/*$/)[1];var c=R(b,a);a:{try{var d=R(b,a)}catch(g){d=g.L;break a}var e=W(b,"wx");d=e?e:Q(d.mode)?31:0}if(d)throw new O(d);if(!b.u.unlink)throw new O(63);if(c.K)throw new O(10);b.u.unlink(b,a);ob(c)}function Mb(a,b){a="string"==typeof a?U(a,{O:!0}).node:a;Fb(a,{mode:b&4095|a.mode&-4096,ctime:Date.now(),sa:void 0})}
function Nb(a,b){if(""===a)throw new O(44);if("string"==typeof b){var c={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof c)throw Error(`Unknown file open mode: ${b}`);b=c}c=b&64?33206:0;if("object"==typeof a)var d=a;else{var e=a.endsWith("/");a=U(a,{O:!(b&131072),ia:!0});d=a.node;a=a.path}var g=!1;if(b&64)if(d){if(b&128)throw new O(20);}else{if(e)throw new O(31);d=Hb(a,c|511,0);g=!0}if(!d)throw new O(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!Q(d.mode))throw new O(54);
if(!g&&(e=d?40960===(d.mode&61440)?32:Q(d.mode)&&("r"!==Cb(b)||b&576)?31:W(d,Cb(b)):44))throw new O(e);if(b&512&&!g){e=d;e="string"==typeof e?U(e,{O:!0}).node:e;if(Q(e.mode))throw new O(31);if(32768!==(e.mode&61440))throw new O(28);var h=W(e,"w");if(h)throw new O(h);Fb(e,{size:0,timestamp:Date.now()})}b&=-131713;e={node:d,path:V(d),flags:b,seekable:!0,position:0,v:d.v,ja:[],error:!1};h=-1;e=Object.assign(new zb,e);if(-1==h)a:{for(h=0;4096>=h;h++)if(!S[h])break a;throw new O(33);}e.fd=h;S[h]=e;e.v.open&&
e.v.open(e);g&&Mb(d,c&511);!f.logReadFiles||b&1||a in yb||(yb[a]=1);return e}
function Ob(a,b,c,d,e,g){if(0>d||0>e)throw new O(28);if(null===a.fd)throw new O(8);if(0===(a.flags&2097155))throw new O(8);if(Q(a.node.mode))throw new O(31);if(!a.v.write)throw new O(28);if(a.seekable&&a.flags&1024){if(null===a.fd)throw new O(8);if(!a.seekable||!a.v.B)throw new O(70);a.position=a.v.B(a,0,2);a.ja=[]}var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new O(70);b=a.v.write(a,b,c,d,e,g);h||(a.position+=b);return b}
function Pb(a,b){a="string"==typeof a?a:V(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=N(a+"/"+c);try{X(d)}catch(e){if(20!=e.L)throw e;}a=d}}return d}function Qb(a,b,c,d){a=N(("string"==typeof a?a:V(a))+"/"+b);return Ib(a,pb(c,d))}
function Rb(a,b,c,d,e,g){var h=b;a&&(a="string"==typeof a?a:V(a),h=b?N(a+"/"+b):a);a=pb(d,e);h=Ib(h,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Mb(h,a|146);b=Nb(h,577);Ob(b,c,0,c.length,0,g);if(null===b.fd)throw new O(8);b.ea&&(b.ea=null);try{b.v.close&&b.v.close(b)}catch(q){throw q;}finally{S[b.fd]=null}b.fd=null;Mb(h,a)}}
function Z(a,b,c,d){a=N(("string"==typeof a?a:V(a))+"/"+b);b=pb(!!c,!!d);Z.$??(Z.$=64);var e=Z.$++<<8|0;ib(e,{open(g){g.seekable=!1},close(){d?.buffer?.length&&d(10)},read(g,h,q,p){for(var l=0,n=0;n<p;n++){try{var r=c()}catch(C){throw new O(29);}if(void 0===r&&0===l)throw new O(6);if(null===r||void 0===r)break;l++;h[q+n]=r}l&&(g.node.atime=Date.now());return l},write(g,h,q,p){for(var l=0;l<p;l++)try{d(h[q+l])}catch(n){throw new O(29);}p&&(g.node.mtime=g.node.ctime=Date.now());return l}});return Jb(a,
b,e)}function Sb(a){if(!(a.fa||a.ga||a.link||a.s))if(globalThis.XMLHttpRequest)D("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.s=v(a.url)}catch(b){throw new O(29);}}
function Tb(a,b,c,d,e){class g{U=!1;G=[];T=void 0;W=0;V=0;get(l){if(!(l>this.length-1||0>l)){var n=l%this.chunkSize;return this.T(l/this.chunkSize|0)[n]}}da(l){this.T=l}X(){var l=new XMLHttpRequest;l.open("HEAD",c,!1);l.send(null);200<=l.status&&300>l.status||304===l.status||D("Couldn't load "+c+". Status: "+l.status);var n=Number(l.getResponseHeader("Content-length")),r,C=(r=l.getResponseHeader("Accept-Ranges"))&&"bytes"===r;l=(r=l.getResponseHeader("Content-Encoding"))&&"gzip"===r;var w=1048576;
C||(w=n);var t=this;t.da(K=>{var Y=K*w,L=(K+1)*w-1;L=Math.min(L,n-1);if("undefined"==typeof t.G[K]){var $b=t.G;Y>L&&D("invalid range ("+Y+", "+L+") or no bytes requested!");L>n-1&&D("only "+n+" bytes available! programmer error!");var u=new XMLHttpRequest;u.open("GET",c,!1);n!==w&&u.setRequestHeader("Range","bytes="+Y+"-"+L);u.responseType="arraybuffer";u.overrideMimeType&&u.overrideMimeType("text/plain; charset=x-user-defined");u.send(null);200<=u.status&&300>u.status||304===u.status||D("Couldn't load "+
c+". Status: "+u.status);Y=void 0!==u.response?new Uint8Array(u.response||[]):fb(u.responseText||"");$b[K]=Y}"undefined"==typeof t.G[K]&&D("doXHR failed!");return t.G[K]});if(l||!n)w=n=1,w=n=this.T(0).length,ja("LazyFiles on gzip forces download of the whole file when length is accessed");this.W=n;this.V=w;this.U=!0}get length(){this.U||this.X();return this.W}get chunkSize(){this.U||this.X();return this.V}}if(globalThis.XMLHttpRequest){k||D("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");
var h=new g;var q=void 0}else q=c,h=void 0;var p=Qb(a,b,d,e);h?p.s=h:q&&(p.s=null,p.url=q);Object.defineProperties(p,{A:{get:function(){return this.s.length}}});a={};for(const [l,n]of Object.entries(p.v))a[l]=(...r)=>{Sb(p);return n(...r)};a.read=(l,n,r,C,w)=>{Sb(p);l=l.node.s;if(w>=l.length)n=0;else{C=Math.min(l.length-w,C);if(l.slice)for(var t=0;t<C;t++)n[r+t]=l[w+t];else for(t=0;t<C;t++)n[r+t]=l.get(w+t);n=C}return n};a.R=()=>{Sb(p);D();throw new O(48);};p.v=a;return p}var Ub={};
f.requestAnimationFrame=Ja;f.pauseMainLoop=Va;f.resumeMainLoop=function(){Ma++;var a=Fa,b=Ga,c=H;H=null;Ua(c,0,!1,Na,!0);La(a,b);I()};f.preMainLoop&&Sa.push(f.preMainLoop);f.postMainLoop&&Ta.push(f.postMainLoop);T=Array(4096);Gb(P,"/");X("/tmp");X("/home");X("/home/web_user");
(function(){X("/dev");ib(259,{read:()=>0,write:(d,e,g,h)=>h,B:()=>0});Jb("/dev/null",259);hb(1280,kb);hb(1536,lb);Jb("/dev/tty",1280);Jb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Za(a),b=a.byteLength);return a[--b]};Z("/dev","random",c);Z("/dev","urandom",c);X("/dev/shm");X("/dev/shm/tmp")})();
(function(){X("/proc");var a=X("/proc/self");X("/proc/self/fd");Gb({F(){var b=nb(a,"fd",16895,73);b.v={B:P.v.B};b.u={lookup(c,d){c=+d;var e=Eb(c);c={parent:null,F:{aa:"fake"},u:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(S.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();f.noExitRuntime&&(za=f.noExitRuntime);f.preloadPlugins&&(rb=f.preloadPlugins);f.print&&(ja=f.print);f.printErr&&(x=f.printErr);f.wasmBinary&&(y=f.wasmBinary);
f.arguments&&(ba=f.arguments);f.thisProgram&&(ca=f.thisProgram);if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();f.addRunDependency=ya;f.removeRunDependency=xa;f.FS_preloadFile=async(a,b,c,d,e,g,h,q)=>{var p=b?$a(N(a+"/"+b)):a,l=`cp ${p}`;ya(l);try{var n=c;"string"==typeof c&&(n=await qb(c));n=await sb(n,p);q?.();g||Rb(a,b,n,d,e,h)}finally{xa(l)}};f.FS_unlink=(...a)=>Lb(...a);f.FS_createPath=(...a)=>Pb(...a);f.FS_createDevice=(...a)=>Z(...a);
f.FS_createDataFile=(...a)=>Rb(...a);f.FS_createLazyFile=(...a)=>Tb(...a);
var Vb,Wb,Xb,na,Yb,Zb={b:()=>D(""),a:()=>{za=!1;Aa=0},c:(a,b)=>{G[a]&&(clearTimeout(G[a].id),delete G[a]);if(!b)return 0;var c=setTimeout(()=>{delete G[a];Ea(()=>Wb(a,performance.now()))},b);G[a]={id:c,Ca:b};return 0},j:()=>{Va();H=null},f:()=>Date.now(),d:a=>{var b=la.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-na.buffer.byteLength+65535)/65536|0;try{na.grow(d);ma();var e=
1;break a}catch(g){}e=void 0}if(e)return!0}return!1},k:(a,b,c)=>{a=Yb.get(a);Ua(a,b,c)},e:function(a,b,c,d){try{a:{var e=Eb(a);a=b;for(var g,h=b=0;h<c;h++){var q=B[a>>2],p=B[a+4>>2];a+=8;var l=Ob(e,A,q,p,g);if(0>l){var n=-1;break a}b+=l;if(l<p)break;"undefined"!=typeof g&&(g+=l)}n=b}B[d>>2]=n;return 0}catch(r){if("undefined"==typeof Ub||"ErrnoError"!==r.name)throw r;return r.L}},h:function(){return"undefined"!==typeof termCols?termCols:120},g:function(){return"undefined"!==typeof termRows?termRows:
40},i:Ca};function ac(a=[]){var b=Vb;a.unshift(ca);var c=a.length,d=Xb(4*(c+1)),e=d,g;for(g of a){a=B;var h=e>>2,q=g,p=db(q)+1,l=Xb(p);eb(q,la,l,p);a[h]=l;e+=4}B[e>>2]=0;try{var n=b(c,d);ka=n;Ca(n)}catch(r){Ba(r)}}
function bc(a=ba){function b(){f.calledRun=!0;if(!z){if(!f.noFSInit&&!wb){var c,d;wb=!0;c??=f.stdin;d??=f.stdout;e??=f.stderr;c?Z("/dev","stdin",c):Kb("/dev/tty","/dev/stdin");d?Z("/dev","stdout",null,d):Kb("/dev/tty","/dev/stdout");e?Z("/dev","stderr",null,e):Kb("/dev/tty1","/dev/stderr");Nb("/dev/stdin",0);Nb("/dev/stdout",1);Nb("/dev/stderr",1)}cc.m();xb=!1;f.onRuntimeInitialized?.();f.noInitialRun||ac(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var e=
f.postRun.shift();ua.push(e)}ta(ua)}}if(0<E)F=bc;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)wa();ta(va);0<E?F=bc:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b()}}var cc;
(async function(){function a(c){c=cc=c.exports;Vb=f._main=c.n;Wb=c.p;Xb=c.q;na=c.l;Yb=c.o;ma();xa("wasm-instantiate");return cc}ya("wasm-instantiate");var b={a:Zb};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{c(a(d,e))})});oa??=f.locateFile?f.locateFile("shooter.wasm",fa):fa+"shooter.wasm";return a((await ra(b)).instance)})();bc();
